# Generated by Django 6.0.7 on 2026-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='current_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='page_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='page_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='required_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.TextField(blank=True),
        ),
    ]
