# Generated by Django 6.0.7 on 2026-08-20 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_linkedin_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedinconnection',
            options={'verbose_name': 'LinkedIn Connection', 'verbose_name_plural': 'LinkedIn Connection'},
        ),
        migrations.AlterModelOptions(
            name='linkedinpost',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='linkedinconnection',
            name='connected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
