# Generated by Django 6.0.7 on 2026-08-25 04:54

from django.db import migrations, models


def assign_existing_category_order(apps, schema_editor):
    ServiceCategory = apps.get_model("website", "ServiceCategory")
    for index, category in enumerate(ServiceCategory.objects.order_by("name", "pk"), start=1):
        category.display_order = index * 10
        category.save(update_fields=["display_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_linkedinconnection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional custom icon. This is shown before the automatic icon.', null=True, upload_to='services/icons/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first.'),
        ),
        migrations.RunPython(assign_existing_category_order, migrations.RunPython.noop),
    ]
