# Generated by Django 6.0.5 on 2026-09-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_customerprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentscheme',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Incubation Scheme', 'verbose_name_plural': 'Incubation Schemes'},
        ),
    ]
